Modify verify for testing

diff --git a/.github/workflows/app-verify.yml b/.github/workflows/app-verify.yml
--- a/.github/workflows/app-verify.yml
+++ b/.github/workflows/app-verify.yml
@@ -4,6 +4,9 @@ on:
   pull_request:
     paths-ignore:
       - 'docs/**'
+  push:
+    branches:
+      - single-function
 
 jobs:
   verify-build:
@@ -18,146 +21,176 @@ jobs:
         with:
           node-version: 10
 
-      - name: Get cache settings
-        id: cache-settings
-        run: |
-          echo "::set-output name=dir::$(yarn cache dir)"
-          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
-
-      - name: Get Yarn Cache
-        id: yarn-cache
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      - name: Cache NPM Dependencies
-        uses: actions/cache@v1
+      - name: Setup Google CLI
+        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
         with:
-          path: ${{ steps.yarn-cache.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          version: '290.0.1'
+          project_id: ${{ env.GCLOUD_PROJECT }}
+          service_account_key: ${{ env.MASTER_SERVICE_ACCOUNT }}
+          export_default_credentials: true
 
-      - name: Install Dependencies
+      - name: Get list of functions to deploy
         env:
-          CYPRESS_INSTALL_BINARY: 0 # Skip installing of cypress
+          SHA: ${{ github.sha }}
         run: |
-          yarn install --frozen-lockfile
-          yarn --cwd functions install --frozen-lockfile
+          # App Version
+          version=v$(cat package.json | jq .version -r)
+          cacheFolderPath="functions_deploy_cache/current"
+          localFolderPath="$HOME/local-functions-cache"
+          targets=""
+          # TODO: Confirm that this local cache is not being uploaded in functions or app deploys
+          # TODO: Check for changes in packages.json, utils and constants folders
+          gsutil -m cp -r gs://$GCLOUD_PROJECT.appspot.com/$cacheFolderPath $localFolderPath
+          echo "Downloaded files"
+          for f in $(diff -Nqr functions/src/ $localFolderPath/ | awk '{print $4}' | cut -d'/' -f2-); do
+            functionName=$(echo ${f%?????} | sed -r 's/[\/]([a-z])/\U\2/g')
+            echo $functionName
+            targets="${target} functions:${functionName}"
+          done
+          gsutil -m rsync -d -r functions/src gs://$GCLOUD_PROJECT.appspot.com/$cacheFolderPath
+          echo "Function deploy targets $targets"
+          echo "::set-env name=FUNCTIONS_DEPLOY_COMMAND::$targets"
 
-      - name: Archive Error Logs
-        uses: actions/upload-artifact@v2
-        if: failure()
-        with:
-          name: error-logs
-          path: yarn-error.log
+  #     - name: Get cache settings
+  #       id: cache-settings
+  #       run: |
+  #         echo "::set-output name=dir::$(yarn cache dir)"
+  #         echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
 
-      - name: Build App Config
-        env:
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
-        run: yarn build:config
+  #     - name: Get Yarn Cache
+  #       id: yarn-cache
+  #       run: echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: Verify Functions
-        # NOTE: Project name is hardcoded since emulators are being used
-        run: |
-          yarn functions:build
-          yarn --cwd functions test:cov || echo "::warning::Functions unit tests failed"
+  #     - name: Cache NPM Dependencies
+  #       uses: actions/cache@v1
+  #       with:
+  #         path: ${{ steps.yarn-cache.outputs.dir }}
+  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
 
-      - name: Upload Functions Test Coverage
-        run: |
-          bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || 'Test Coverage Upload Failed, continuing'
+  #     - name: Install Dependencies
+  #       env:
+  #         CYPRESS_INSTALL_BINARY: 0 # Skip installing of cypress
+  #       run: |
+  #         yarn install --frozen-lockfile
+  #         yarn --cwd functions install --frozen-lockfile
 
-      - name: Verify
-        run: yarn lint
+  #     - name: Archive Error Logs
+  #       uses: actions/upload-artifact@v2
+  #       if: failure()
+  #       with:
+  #         name: error-logs
+  #         path: yarn-error.log
 
-      - name: Build App
-        run: |
-          export REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST="localhost:$(cat firebase.json | jq .emulators.database.port)"
-          export REACT_APP_FIRESTORE_EMULATOR_HOST="localhost:$(cat firebase.json | jq .emulators.firestore.port)"
-          yarn build
+  #     - name: Build App Config
+  #       env:
+  #         GITHUB_HEAD_REF: ${{ github.head_ref }}
+  #         GITHUB_REF: ${{ github.ref }}
+  #       run: yarn build:config
 
-      - name: Archive Build Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: build
-          path: build
+  #     - name: Verify Functions
+  #       # NOTE: Project name is hardcoded since emulators are being used
+  #       run: |
+  #         yarn functions:build
+  #         yarn --cwd functions test:cov || echo "::warning::Functions unit tests failed"
 
-  ui-tests:
-    name: UI Test Emulated App
-    needs: verify-build
-    runs-on: ubuntu-16.04
-    strategy:
-      # Keep all in-progress jobs running if any matrix job fails. Needed to prevent
-      # the Cypress Dashboard from being stuck in "in progress" state since not all tests run.
-      # See the following for more details:
-      # * Cypress Action Issue: https://github.com/cypress-io/github-action/issues/48
-      # * Docs for fail-fast: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
-      fail-fast: false
-      matrix:
-        # Run multiple copies of the current job in parallel
-        containers: [1, 2, 3, 4]
-    steps:
-      - name: Setup Node
-        uses: actions/setup-node@v1
-        with:
-          node-version: 10
+  #     - name: Upload Functions Test Coverage
+  #       run: |
+  #         bash <(curl -s https://codecov.io/bash) -f functions/coverage/lcov.info || 'Test Coverage Upload Failed, continuing'
 
-      - name: Checkout Repo
-        uses: actions/checkout@v2
+  #     - name: Verify
+  #       run: yarn lint
 
-      - name: Get Cache Settings
-        id: cache-settings
-        run: |
-          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
+  #     - name: Build App
+  #       run: |
+  #         export REACT_APP_FIREBASE_DATABASE_EMULATOR_HOST="localhost:$(cat firebase.json | jq .emulators.database.port)"
+  #         export REACT_APP_FIRESTORE_EMULATOR_HOST="localhost:$(cat firebase.json | jq .emulators.firestore.port)"
+  #         yarn build
 
-      - name: Cache Firebase Emulator Binaries
-        uses: actions/cache@v1
-        with:
-          path: ~/.cache/firebase/emulators
-          key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
+  #     - name: Archive Build Artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: build
+  #         path: build
 
-      - name: Set Test Environment Settings
-        id: emulator-settings
-        env:
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
-        run: |
-          export GIT_BRANCH=${GITHUB_REF##*/}
-          export GCLOUD_PROJECT=$(cat .firebaserc | jq -r --arg GIT_BRANCH "$GIT_BRANCH" '.projects[$GIT_BRANCH] // .projects.master')
-          echo "::set-env name=GCLOUD_PROJECT::$GCLOUD_PROJECT"
-          echo "Environment set for branch: $GIT_BRANCH and project: $GCLOUD_PROJECT"
-          echo "Setting emulator settings to environment..."
-          echo "::set-env name=FIREBASE_DATABASE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.database.port)"
-          echo "::set-env name=FIRESTORE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.firestore.port)"
-          echo "::set-env name=CYPRESS_BASE_URL::http://localhost:$(cat package.json | jq .config.port)"
-          echo "Generating Service Account File..."
-          echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
-          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+  # ui-tests:
+  #   name: UI Test Emulated App
+  #   needs: verify-build
+  #   runs-on: ubuntu-16.04
+  #   strategy:
+  #     # Keep all in-progress jobs running if any matrix job fails. Needed to prevent
+  #     # the Cypress Dashboard from being stuck in "in progress" state since not all tests run.
+  #     # See the following for more details:
+  #     # * Cypress Action Issue: https://github.com/cypress-io/github-action/issues/48
+  #     # * Docs for fail-fast: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
+  #     fail-fast: false
+  #     matrix:
+  #       # Run multiple copies of the current job in parallel
+  #       containers: [1, 2, 3, 4]
+  #   steps:
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 10
 
-      - name: Download Build Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: build
-          path: build
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v2
 
-      # Cypress action manages installing/caching npm dependencies and Cypress binary.
-      # Because of "record" and "parallel" parameters these containers will load
-      # balance all found tests among themselves. The step tests a version of the app
-      # which is running locally in the container on port 3000
-      - name: Cypress Run
-        uses: cypress-io/github-action@v1
-        with:
-          browser: chrome
-          parallel: true
-          record: true
-          headless: true
-          group: 'UI Integration Tests'
-          tag: emulated
-          start: yarn emulate:all --project ${{ env.GCLOUD_PROJECT }}
-          wait-on: ${{ env.CYPRESS_BASE_URL }}
-          wait-on-timeout: 120
-        env:
-          TZ: America/Los_Angeles
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
-          GITHUB_HEAD_REF: ${{ github.head_ref }}
-          GITHUB_REF: ${{ github.ref }}
-          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
-          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
+  #     - name: Get Cache Settings
+  #       id: cache-settings
+  #       run: |
+  #         echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
+
+  #     - name: Cache Firebase Emulator Binaries
+  #       uses: actions/cache@v1
+  #       with:
+  #         path: ~/.cache/firebase/emulators
+  #         key: ${{ runner.os }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}
+
+  #     - name: Set Test Environment Settings
+  #       id: emulator-settings
+  #       env:
+  #         GITHUB_HEAD_REF: ${{ github.head_ref }}
+  #         GITHUB_REF: ${{ github.ref }}
+  #       run: |
+  #         export GIT_BRANCH=${GITHUB_REF##*/}
+  #         export GCLOUD_PROJECT=$(cat .firebaserc | jq -r --arg GIT_BRANCH "$GIT_BRANCH" '.projects[$GIT_BRANCH] // .projects.master')
+  #         echo "::set-env name=GCLOUD_PROJECT::$GCLOUD_PROJECT"
+  #         echo "Environment set for branch: $GIT_BRANCH and project: $GCLOUD_PROJECT"
+  #         echo "Setting emulator settings to environment..."
+  #         echo "::set-env name=FIREBASE_DATABASE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.database.port)"
+  #         echo "::set-env name=FIRESTORE_EMULATOR_HOST::localhost:$(cat firebase.json | jq .emulators.firestore.port)"
+  #         echo "::set-env name=CYPRESS_BASE_URL::http://localhost:$(cat package.json | jq .config.port)"
+  #         echo "Generating Service Account File..."
+  #         echo "$(echo $SERVICE_ACCOUNT | jq .)" > $HOME/serviceAccount.json
+  #         echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::$HOME/serviceAccount.json"
+
+  #     - name: Download Build Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: build
+  #         path: build
+
+  #     # Cypress action manages installing/caching npm dependencies and Cypress binary.
+  #     # Because of "record" and "parallel" parameters these containers will load
+  #     # balance all found tests among themselves. The step tests a version of the app
+  #     # which is running locally in the container on port 3000
+  #     - name: Cypress Run
+  #       uses: cypress-io/github-action@v1
+  #       with:
+  #         browser: chrome
+  #         parallel: true
+  #         record: true
+  #         headless: true
+  #         group: 'UI Integration Tests'
+  #         tag: emulated
+  #         start: yarn emulate:all --project ${{ env.GCLOUD_PROJECT }}
+  #         wait-on: ${{ env.CYPRESS_BASE_URL }}
+  #         wait-on-timeout: 120
+  #       env:
+  #         TZ: America/Los_Angeles
+  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
+  #         GITHUB_HEAD_REF: ${{ github.head_ref }}
+  #         GITHUB_REF: ${{ github.ref }}
+  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+  #         SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
+  #         CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
